version: "3" # Docker Version
services:
    node-server:
        build: .
        ports:
            - "8000:8000"
    db:
        image: mysql:8.0
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tutorial
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - db
